CUDA is not available. Using CPU instead.
{'name': 'ProcessedDataset', 'path': 'data/ML1M_pro/1', 'device': device(type='cpu'), 'split_ratio': [0.7, 0.1, 0.2], 'min_inter': 10, 'n_groups': 10, 'gamma': 1.826}
init dataset ProcessedDataset
num of users 1 num of items 0 
num of edges 0 num of training edges 0
{'name': 'LightGCN', 'embedding_size': 64, 'device': device(type='cpu'), 'n_layers': 3, 'dataset': <dataset.ProcessedDataset object at 0x12a137d60>}
Traceback (most recent call last):
  File "/Users/lucas/IPL/run.py", line 105, in <module>
    main()
  File "/Users/lucas/IPL/run.py", line 75, in main
    model = get_model(model_config, dataset)
  File "/Users/lucas/IPL/model.py", line 16, in get_model
    model = model(config)
  File "/Users/lucas/IPL/model.py", line 81, in __init__
    self.norm_adj = self.generate_graph(model_config['dataset'])
  File "/Users/lucas/IPL/model.py", line 89, in generate_graph
    adj_mat = generate_daj_mat(dataset)
  File "/Users/lucas/IPL/utils.py", line 40, in generate_daj_mat
    users, items = train_array[:, 0], train_array[:, 1]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
